[package]
name = "libguttt"
version = "0.1.0"
authors = ["Kimapr <dmitriy.tillyaev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "libguttt"
path = "src/lib.rs"
